#!/bin/bash
source /software/modules/init/bash
module purge
module load circ 
module load anaconda3
export TMP=`local_scratch`

#load qiime environment
source activate ###UPDATE FULL PATH TO CONDA ENV###
python3 $@
